# Generated by Django 4.2.3 on 2023-07-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(choices=[('', 'Выберите оператор'), ('900', 'Билайн (900)'), ('901', 'МТС (901)'), ('902', 'Мегафон (902)'), ('903', 'Теле2 (903)')], max_length=3, verbose_name='Код Оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=7, verbose_name='Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(max_length=150, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(choices=[('Europe/Kaliningrad', 'Калининград - UTC+2'), ('Europe/Moscow', 'Москва - UTC+3'), ('Europe/Samara', 'Самара - UTC+4'), ('Asia/Yekaterinburg', 'Екатеринбург - UTC+5'), ('Asia/Omsk', 'Омск - UTC+6'), ('Asia/Novosibirsk', 'Новосибирск - UTC+7'), ('Asia/Irkutsk', 'Иркутск - UTC+8'), ('Asia/Yakutsk', 'Якутск - UTC+9'), ('Asia/Vladivostok', 'Владивосток - UTC+10'), ('Asia/Magadan', 'Магадан - UTC+11'), ('Asia/Srednekolymsk', 'Среднеколымск - UTC+11'), ('Asia/Kamchatka', 'Петропавловск-Камчатский - UTC+12')], max_length=100, verbose_name='Часовой Пояс'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='operator_code',
            field=models.CharField(choices=[('', 'Выберите оператор'), ('900', 'Билайн (900)'), ('901', 'МТС (901)'), ('902', 'Мегафон (902)'), ('903', 'Теле2 (903)')], max_length=3, verbose_name='Код Оператора'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_status',
            field=models.CharField(choices=[('Не отправлено', 'Не отправлено'), ('В процессе', 'В процессе'), ('Доставлено', 'Доставлено')], default='Не отправлено', max_length=255, verbose_name='Статус Сообщения'),
        ),
    ]
