# Generated by Django 4.2.3 on 2023-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_remove_client_tag_remove_mailing_tag_client_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='tag',
            field=models.ManyToManyField(related_name='mailings', to='api.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(verbose_name='Дата Создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_status',
            field=models.CharField(choices=[('Не отправлено', 'Не отправлено'), ('В процессе', 'В процессе'), ('Доставлено', 'Доставлено')], default='В процессе', max_length=255, verbose_name='Статус Сообщения'),
        ),
    ]
