# Generated by Django 4.2.3 on 2023-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mailing_tag_alter_message_creation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag',
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='api.tag', verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='api.tag', verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
